[project]
name = "uviolet"
version = "0.1.0"
description = "Learn uv, a project from Astral for managing python projects and much more."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ruff>=0.11.0",
]
